/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package add;

import org.junit.Test;
import com.amazonaws.services.lambda.runtime.Context;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testAddTwo() {
    }

    @Test public void testAddNumbers() {
    }
}
