/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ddb;

import com.amazonaws.AmazonServiceException;
import com.amazonaws.regions.Regions;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDB;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDBClientBuilder;
import com.amazonaws.services.dynamodbv2.document.DynamoDB;
import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.amazonaws.services.dynamodbv2.model.AttributeValue;
import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.LambdaLogger;


import java.util.*;

public class Library {

    private DynamoDB dynamoDb;
    private String DYNAMODB_TABLE_NAME = "people";
    private Regions REGION = Regions.US_WEST_2;

    public Customer save(int num, Context context) {
        Customer customer = new Customer();
        customer.setName( "John" );
        customer.setOld( true );

        final AmazonDynamoDB ddb = AmazonDynamoDBClientBuilder.defaultClient();
        DynamoDBMapper ddbMapper = new DynamoDBMapper(ddb);

        ddbMapper.save(customer);

        return customer;
    }
}

