/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import com.google.gson.Gson;

import java.io.*;
import java.util.Scanner;

public class App {

    public static void main(String[] args) throws FileNotFoundException {
        Gson gson = new Gson();
        System.out.println(gson.toJson(new int[]{1,2,3}));

//        Unicorn u = new Unicorn("Jessica", "purple", true);
////        System.out.println(u);
////        String unicornString = gson.toJson(u);
////        u.frolic();

        Scanner reader = new Scanner(new File("src/main/resources/unicorns.json"));
        String unicornString = reader.nextLine();
        System.out.println(unicornString);
        Unicorn unicornFromFile = gson.fromJson(unicornString, Unicorn.class);
        System.out.println(unicornFromFile);

        Donut donutFromFile = gson.fromJson(unicornString, Donut.class);
        System.out.println(donutFromFile);
    }

    public static void writeUnicornToFile(String unicornString) {

        BufferedWriter writer = null;
        try {
            writer = new BufferedWriter(new FileWriter("src/main/resources/unicorns.json"));
            writer.write(unicornString);
            writer.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
