/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

public class App {

    public static void main(String[] args) {
        System.out.println(getGreeting());
    }

    public static String getGreeting() {
        return "Hello world.";
    }

}
