/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap_transformer;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

public class App {

    public static void main(String[] args) throws IOException {
        BufferedImage i = ImageIO.read(new File("src/main/resources/Coffee.bmp"));
        Bitmap myBitmap = new Bitmap(i);
        // transforms happen here? eventually
        myBitmap.paintItBlack();
        myBitmap.writeToFile("src/main/resources/CoffeePaintedBlack.bmp");

    }
}
