/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package add;

import org.junit.Test;
import com.amazonaws.services.lambda.runtime.Context;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testAddTwo() {
        Library classUnderTest = new Library();
        assertEquals("addTwo should return 3", 3, classUnderTest.addTwo(1));
    }

    @Test public void testAddNumbers() {
        Library classUnderTest = new Library();
        Numbers nums = new Numbers(1,3);
        assertEquals("addNumbers should return 4", 4, classUnderTest.addNumbers(nums));
    }
}
