/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fileIO;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        getAliceInWonderland();
    }

    // scanning came from https://docs.oracle.com/javase/tutorial/essential/io/scanning.html
    public static void getAliceInWonderland() {
        Scanner s = null;

        int timesAliceIsMentioned = 0;
        try {
            s = new Scanner(new BufferedReader(new FileReader("./src/main/resources/alice.txt")));
            while (s.hasNext()) {
                if (s.next().contains("Alice")) {
                    timesAliceIsMentioned++;
                }
            }
            System.out.println(String.format("Alice is mentioned %d times.", timesAliceIsMentioned));
        } catch (FileNotFoundException e) {
            System.out.println("the file was not found");
        }
    }
}
