/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package add;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.LambdaLogger;

public class Library {

    // Build this simple function first, just to get proof of life here and at AWS
    public int addTwo(int a ) {
        return a + 2;
    }

    // Next, build this, to demonstrate how you can use the AWS Context object to use their "console"
    public int addTwoWithContext(int a, Context context ) {
        int sum = a + 2;
        LambdaLogger logger = context.getLogger();
        logger.log("The answer is: " + sum);
        return sum;
    }

    // Build this out in stages
    public int addNumbers( Numbers nums) {
        int sum = nums.a + nums.b;
        return sum;
    }

    // The same thing, but with context (done right)
    public int addNumbersWithContext( Numbers nums, Context context) {
        int sum = nums.a + nums.b;
        LambdaLogger logger = context.getLogger();
        logger.log("The answer is: " + sum);
        return sum;
    }

}

class Numbers {
    // Initially, just build this
    int a;
    int b;

    // Presume you're going to get the constructor called. But you get a zero as the result.

    // Build out the empty constructor and see if that works.
    public Numbers() {}

    // Build it out with params
    public Numbers( int a, int b) {
        this.a = a;
        this.b = b;
    }

    // Finally, create your setters to get it working at AWS
    public void setA(int a) {
        this.a = a;
    }

    public void setB(int b) {
        this.b = b;
    }
}
