/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {

    @Test
    public void testMain() {
        App.main(new String[]{});
    }

    @Test
    public void testGetRandomQuote() {
        // Things I can definitely test:
        // did I get null?
        // did I get a quote actually in the array that was input?

        // probability: run it twice, see if you get the same thing
        // dangerous! maybe flaky tests
        // flaky is good for biscuits
        // not for tests
        // run it many many many times and make sure it's doing reasonably well

        // Things I need to guard against:
        // getting nothing (aka null)
        // getting the same answer every time

        // break it down into a random number generator and the thing that uses the random number


        // make an array of 2 quotes (maybe 3? if I'm feeling fancy)
        // run the picker 200 times
        // check that each was picked between 90-110 times

    }
}
