/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.Reader;

public class App {

    public static void main(String[] args) {
        // read in a file & convert to Quote array
        Gson gson  = new Gson();
        try {
            Quote[] quotes = gson.fromJson(
                    new FileReader("src/main/resources/recentquotes.json"),
                    Quote[].class);
            Quote randomQuote = getRandomQuote(quotes);
            System.out.println(randomQuote);
        } catch (FileNotFoundException e) {
            System.out.println("error reading file");
        }
        // pick random quote from array
        // display quote
    }

    // Given a reader for some JSON data representing quotes, return a Quote[]
    public static Quote[] getQuotes(Reader quoteData) {
        Gson gson  = new Gson();
        Quote[] quotes = gson.fromJson(
                quoteData,
                Quote[].class);
        return quotes;
    }
    // Given an array of quotes, returns a random quote.
    public static Quote getRandomQuote(Quote[] quotes) {
        return quotes[(int)(Math.random() * quotes.length)];
    }
}
